//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package com.cv.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CoverLetterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoverLetterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Addressee" type="{http://europass.cedefop.europa.eu/Europass}AddresseeType" minOccurs="0"/>
 *         &lt;element name="Letter" type="{http://europass.cedefop.europa.eu/Europass}LetterType" minOccurs="0"/>
 *         &lt;element name="Documentation" type="{http://europass.cedefop.europa.eu/Europass}GenericDocumentationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoverLetterType", propOrder = {
    "addressee",
    "letter",
    "documentation"
})
public class CoverLetterType {

    @XmlElement(name = "Addressee")
    protected AddresseeType addressee;
    @XmlElement(name = "Letter")
    protected LetterType letter;
    @XmlElement(name = "Documentation")
    protected GenericDocumentationType documentation;

    /**
     * Gets the value of the addressee property.
     * 
     * @return
     *     possible object is
     *     {@link AddresseeType }
     *     
     */
    public AddresseeType getAddressee() {
        return addressee;
    }

    /**
     * Sets the value of the addressee property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddresseeType }
     *     
     */
    public void setAddressee(AddresseeType value) {
        this.addressee = value;
    }

    /**
     * Gets the value of the letter property.
     * 
     * @return
     *     possible object is
     *     {@link LetterType }
     *     
     */
    public LetterType getLetter() {
        return letter;
    }

    /**
     * Sets the value of the letter property.
     * 
     * @param value
     *     allowed object is
     *     {@link LetterType }
     *     
     */
    public void setLetter(LetterType value) {
        this.letter = value;
    }

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link GenericDocumentationType }
     *     
     */
    public GenericDocumentationType getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericDocumentationType }
     *     
     */
    public void setDocumentation(GenericDocumentationType value) {
        this.documentation = value;
    }

}
