//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//

package com.cv.model.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * Defines a skill, the description of which is a driving category. Note that a
 * reference to an attachment may also be added.
 * 
 * 
 * <p>
 * Java class for DrivingSkillType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="DrivingSkillType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://europass.cedefop.europa.eu/Europass}SkillType">
 *       &lt;sequence>
 *         &lt;element name="Description" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Licence" type="{http://europass.cedefop.europa.eu/EUDriving}drivinglicence" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Documentation" type="{http://europass.cedefop.europa.eu/Europass}IntraDocumentDocumentationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DrivingSkillType", propOrder = { "description" })
public class DrivingSkillType {

	@XmlElement(name = "Description")
	protected List<DrivingSkillType.LicenseType> description;

	public List<LicenseType> getDescription() {
		return description;
	}

	public void setDescription(List<LicenseType> description) {
		this.description = description;
	}

	//
	// /**
	// * Gets the value of the description property.
	// *
	// * @return possible object is {@link Object }
	// *
	// */
	// public Drivinglicence getDescription() {
	// return description;
	// }
	//
	// /**
	// * Sets the value of the description property.
	// *
	// * @param value
	// * allowed object is {@link Object }
	// *
	// */
	// public void setDescription(Drivinglicence value) {
	// this.description = value;
	// }
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "licence" })
	public static class LicenseType {

		@XmlElement(name = "Licence")
		protected Drivinglicence licence;

		public Drivinglicence getLicence() {
			return licence;
		}

		public void setLicence(Drivinglicence licence) {
			this.licence = licence;
		}

	}
}
