//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package com.cv.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Contains a headline label for the current document. It is optional and may accommodate various cases.
 * 			
 * 
 * <p>Java class for HeadlineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeadlineType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{http://europass.cedefop.europa.eu/Europass}HeadlineTypeLabelType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://europass.cedefop.europa.eu/Europass}OccupationalFieldType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeadlineType", propOrder = {
    "type",
    "description"
})
@XmlSeeAlso({
    PositionType.class
})
public class HeadlineType {

    @XmlElement(name = "Type")
    protected HeadlineTypeLabelType type;
    @XmlElement(name = "Description")
    protected OccupationalFieldType description;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link HeadlineTypeLabelType }
     *     
     */
    public HeadlineTypeLabelType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadlineTypeLabelType }
     *     
     */
    public void setType(HeadlineTypeLabelType value) {
        this.type = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link OccupationalFieldType }
     *     
     */
    public OccupationalFieldType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link OccupationalFieldType }
     *     
     */
    public void setDescription(OccupationalFieldType value) {
        this.description = value;
    }

}
