//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package com.cv.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LetterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LetterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Localisation" type="{http://europass.cedefop.europa.eu/Europass}LetterLocalisationType" minOccurs="0"/>
 *         &lt;element name="SubjectLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OpeningSalutation" type="{http://europass.cedefop.europa.eu/Europass}OpeningSalutationType" minOccurs="0"/>
 *         &lt;element name="Body" type="{http://europass.cedefop.europa.eu/Europass}BodyType" minOccurs="0"/>
 *         &lt;element name="ClosingSalutation" type="{http://europass.cedefop.europa.eu/Europass}ClosingSalutationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LetterType", propOrder = {
    "localisation",
    "subjectLine",
    "openingSalutation",
    "body",
    "closingSalutation"
})
public class LetterType {

    @XmlElement(name = "Localisation")
    protected LetterLocalisationType localisation;
    @XmlElement(name = "SubjectLine")
    protected String subjectLine;
    @XmlElement(name = "OpeningSalutation")
    protected OpeningSalutationType openingSalutation;
    @XmlElement(name = "Body")
    protected BodyType body;
    @XmlElement(name = "ClosingSalutation")
    protected ClosingSalutationType closingSalutation;

    /**
     * Gets the value of the localisation property.
     * 
     * @return
     *     possible object is
     *     {@link LetterLocalisationType }
     *     
     */
    public LetterLocalisationType getLocalisation() {
        return localisation;
    }

    /**
     * Sets the value of the localisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LetterLocalisationType }
     *     
     */
    public void setLocalisation(LetterLocalisationType value) {
        this.localisation = value;
    }

    /**
     * Gets the value of the subjectLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectLine() {
        return subjectLine;
    }

    /**
     * Sets the value of the subjectLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectLine(String value) {
        this.subjectLine = value;
    }

    /**
     * Gets the value of the openingSalutation property.
     * 
     * @return
     *     possible object is
     *     {@link OpeningSalutationType }
     *     
     */
    public OpeningSalutationType getOpeningSalutation() {
        return openingSalutation;
    }

    /**
     * Sets the value of the openingSalutation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpeningSalutationType }
     *     
     */
    public void setOpeningSalutation(OpeningSalutationType value) {
        this.openingSalutation = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link BodyType }
     *     
     */
    public BodyType getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyType }
     *     
     */
    public void setBody(BodyType value) {
        this.body = value;
    }

    /**
     * Gets the value of the closingSalutation property.
     * 
     * @return
     *     possible object is
     *     {@link ClosingSalutationType }
     *     
     */
    public ClosingSalutationType getClosingSalutation() {
        return closingSalutation;
    }

    /**
     * Sets the value of the closingSalutation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClosingSalutationType }
     *     
     */
    public void setClosingSalutation(ClosingSalutationType value) {
        this.closingSalutation = value;
    }

}
