//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package com.cv.model.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LinguisticSkillType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LinguisticSkillType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MotherTongueList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MotherTongue" type="{http://europass.cedefop.europa.eu/Europass}MotherTongueSkillType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ForeignLanguageList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ForeignLanguage" type="{http://europass.cedefop.europa.eu/Europass}ForeignLanguageSkillType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LinguisticSkillType", propOrder = {
    "motherTongueList",
    "foreignLanguageList"
})
public class LinguisticSkillType {

    @XmlElement(name = "MotherTongueList")
    protected LinguisticSkillType.MotherTongueList motherTongueList;
    @XmlElement(name = "ForeignLanguageList")
    protected LinguisticSkillType.ForeignLanguageList foreignLanguageList;

    /**
     * Gets the value of the motherTongueList property.
     * 
     * @return
     *     possible object is
     *     {@link LinguisticSkillType.MotherTongueList }
     *     
     */
    public LinguisticSkillType.MotherTongueList getMotherTongueList() {
        return motherTongueList;
    }

    /**
     * Sets the value of the motherTongueList property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinguisticSkillType.MotherTongueList }
     *     
     */
    public void setMotherTongueList(LinguisticSkillType.MotherTongueList value) {
        this.motherTongueList = value;
    }

    /**
     * Gets the value of the foreignLanguageList property.
     * 
     * @return
     *     possible object is
     *     {@link LinguisticSkillType.ForeignLanguageList }
     *     
     */
    public LinguisticSkillType.ForeignLanguageList getForeignLanguageList() {
        return foreignLanguageList;
    }

    /**
     * Sets the value of the foreignLanguageList property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinguisticSkillType.ForeignLanguageList }
     *     
     */
    public void setForeignLanguageList(LinguisticSkillType.ForeignLanguageList value) {
        this.foreignLanguageList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ForeignLanguage" type="{http://europass.cedefop.europa.eu/Europass}ForeignLanguageSkillType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "foreignLanguage"
    })
    public static class ForeignLanguageList {

        @XmlElement(name = "ForeignLanguage")
        protected List<ForeignLanguageSkillType> foreignLanguage;

        /**
         * Gets the value of the foreignLanguage property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the foreignLanguage property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getForeignLanguage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ForeignLanguageSkillType }
         * 
         * 
         */
        public List<ForeignLanguageSkillType> getForeignLanguage() {
            if (foreignLanguage == null) {
                foreignLanguage = new ArrayList<ForeignLanguageSkillType>();
            }
            return this.foreignLanguage;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MotherTongue" type="{http://europass.cedefop.europa.eu/Europass}MotherTongueSkillType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "motherTongue"
    })
    public static class MotherTongueList {

        @XmlElement(name = "MotherTongue")
        protected List<MotherTongueSkillType> motherTongue;

        /**
         * Gets the value of the motherTongue property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the motherTongue property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMotherTongue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MotherTongueSkillType }
         * 
         * 
         */
        public List<MotherTongueSkillType> getMotherTongue() {
            if (motherTongue == null) {
                motherTongue = new ArrayList<MotherTongueSkillType>();
            }
            return this.motherTongue;
        }

    }

}
