//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package com.cv.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentInfo" type="{http://europass.cedefop.europa.eu/Europass}DocumentInfoType"/>
 *         &lt;element name="PrintingPreferences" type="{http://europass.cedefop.europa.eu/Europass}PrintingPreferencesType" minOccurs="0"/>
 *         &lt;element name="LearnerInfo" type="{http://europass.cedefop.europa.eu/Europass}LearnerInfoType"/>
 *         &lt;element name="AttachmentList" type="{http://europass.cedefop.europa.eu/Europass}AttachmentListType" minOccurs="0"/>
 *         &lt;element name="CoverLetter" type="{http://europass.cedefop.europa.eu/Europass}CoverLetterType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="locale" use="required" type="{http://europass.cedefop.europa.eu/Europass}LocaleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentInfo",
    "printingPreferences",
    "learnerInfo",
    "attachmentList",
    "coverLetter"
})
@XmlRootElement(name = "SkillsPassport")
public class SkillsPassport {

    @XmlElement(name = "DocumentInfo", required = true)
    protected DocumentInfoType documentInfo;
    @XmlElement(name = "PrintingPreferences")
    protected PrintingPreferencesType printingPreferences;
    @XmlElement(name = "LearnerInfo", required = true)
    protected LearnerInfoType learnerInfo;
    @XmlElement(name = "AttachmentList")
    protected AttachmentListType attachmentList;
    @XmlElement(name = "CoverLetter")
    protected CoverLetterType coverLetter;
    @XmlAttribute(name = "locale", required = true)
    protected String locale;

    /**
     * Gets the value of the documentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentInfoType }
     *     
     */
    public DocumentInfoType getDocumentInfo() {
        return documentInfo;
    }

    /**
     * Sets the value of the documentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentInfoType }
     *     
     */
    public void setDocumentInfo(DocumentInfoType value) {
        this.documentInfo = value;
    }

    /**
     * Gets the value of the printingPreferences property.
     * 
     * @return
     *     possible object is
     *     {@link PrintingPreferencesType }
     *     
     */
    public PrintingPreferencesType getPrintingPreferences() {
        return printingPreferences;
    }

    /**
     * Sets the value of the printingPreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrintingPreferencesType }
     *     
     */
    public void setPrintingPreferences(PrintingPreferencesType value) {
        this.printingPreferences = value;
    }

    /**
     * Gets the value of the learnerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LearnerInfoType }
     *     
     */
    public LearnerInfoType getLearnerInfo() {
        return learnerInfo;
    }

    /**
     * Sets the value of the learnerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearnerInfoType }
     *     
     */
    public void setLearnerInfo(LearnerInfoType value) {
        this.learnerInfo = value;
    }

    /**
     * Gets the value of the attachmentList property.
     * 
     * @return
     *     possible object is
     *     {@link AttachmentListType }
     *     
     */
    public AttachmentListType getAttachmentList() {
        return attachmentList;
    }

    /**
     * Sets the value of the attachmentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentListType }
     *     
     */
    public void setAttachmentList(AttachmentListType value) {
        this.attachmentList = value;
    }

    /**
     * Gets the value of the coverLetter property.
     * 
     * @return
     *     possible object is
     *     {@link CoverLetterType }
     *     
     */
    public CoverLetterType getCoverLetter() {
        return coverLetter;
    }

    /**
     * Sets the value of the coverLetter property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoverLetterType }
     *     
     */
    public void setCoverLetter(CoverLetterType value) {
        this.coverLetter = value;
    }

    /**
     * Gets the value of the locale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocale() {
        return locale;
    }

    /**
     * Sets the value of the locale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocale(String value) {
        this.locale = value;
    }

}
