//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package model.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AchievementTypesEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AchievementTypesEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="honors_awards"/>
 *     &lt;enumeration value="presentations"/>
 *     &lt;enumeration value="publications"/>
 *     &lt;enumeration value="projects"/>
 *     &lt;enumeration value="citations"/>
 *     &lt;enumeration value="memberships"/>
 *     &lt;enumeration value="conferences"/>
 *     &lt;enumeration value="seminars"/>
 *     &lt;enumeration value="workshops"/>
 *     &lt;enumeration value="references"/>
 *     &lt;enumeration value="signature_equivalent"/>
 *     &lt;enumeration value="courses"/>
 *     &lt;enumeration value="certifications"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AchievementTypesEnumeration")
@XmlEnum
public enum AchievementTypesEnumeration {

    @XmlEnumValue("honors_awards")
    HONORS_AWARDS("honors_awards"),
    @XmlEnumValue("presentations")
    PRESENTATIONS("presentations"),
    @XmlEnumValue("publications")
    PUBLICATIONS("publications"),
    @XmlEnumValue("projects")
    PROJECTS("projects"),
    @XmlEnumValue("citations")
    CITATIONS("citations"),
    @XmlEnumValue("memberships")
    MEMBERSHIPS("memberships"),
    @XmlEnumValue("conferences")
    CONFERENCES("conferences"),
    @XmlEnumValue("seminars")
    SEMINARS("seminars"),
    @XmlEnumValue("workshops")
    WORKSHOPS("workshops"),
    @XmlEnumValue("references")
    REFERENCES("references"),
    @XmlEnumValue("signature_equivalent")
    SIGNATURE_EQUIVALENT("signature_equivalent"),
    @XmlEnumValue("courses")
    COURSES("courses"),
    @XmlEnumValue("certifications")
    CERTIFICATIONS("certifications");
    private final String value;

    AchievementTypesEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AchievementTypesEnumeration fromValue(String v) {
        for (AchievementTypesEnumeration c: AchievementTypesEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
