//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Contains all the available methods of contacting individual.
 * 			
 * 
 * <p>Java class for ContactInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContactInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Address" type="{http://europass.cedefop.europa.eu/Europass}ContactAddressType" minOccurs="0"/>
 *         &lt;element name="Email" type="{http://europass.cedefop.europa.eu/Europass}ContactEmailType" minOccurs="0"/>
 *         &lt;element name="TelephoneList" type="{http://europass.cedefop.europa.eu/Europass}TelephoneListType" minOccurs="0"/>
 *         &lt;element name="WebsiteList" type="{http://europass.cedefop.europa.eu/Europass}WebsiteListType" minOccurs="0"/>
 *         &lt;element name="InstantMessagingList" type="{http://europass.cedefop.europa.eu/Europass}InstantMessagingListType" minOccurs="0"/>
 *         &lt;element name="ContactMethodList" type="{http://europass.cedefop.europa.eu/Europass}ContactMethodListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactInfoType", propOrder = {
    "address",
    "email",
    "telephoneList",
    "websiteList",
    "instantMessagingList",
    "contactMethodList"
})
public class ContactInfoType {

    @XmlElement(name = "Address")
    protected ContactAddressType address;
    @XmlElement(name = "Email")
    protected ContactEmailType email;
    @XmlElement(name = "TelephoneList")
    protected TelephoneListType telephoneList;
    @XmlElement(name = "WebsiteList")
    protected WebsiteListType websiteList;
    @XmlElement(name = "InstantMessagingList")
    protected InstantMessagingListType instantMessagingList;
    @XmlElement(name = "ContactMethodList")
    protected ContactMethodListType contactMethodList;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link ContactAddressType }
     *     
     */
    public ContactAddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactAddressType }
     *     
     */
    public void setAddress(ContactAddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link ContactEmailType }
     *     
     */
    public ContactEmailType getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactEmailType }
     *     
     */
    public void setEmail(ContactEmailType value) {
        this.email = value;
    }

    /**
     * Gets the value of the telephoneList property.
     * 
     * @return
     *     possible object is
     *     {@link TelephoneListType }
     *     
     */
    public TelephoneListType getTelephoneList() {
        return telephoneList;
    }

    /**
     * Sets the value of the telephoneList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelephoneListType }
     *     
     */
    public void setTelephoneList(TelephoneListType value) {
        this.telephoneList = value;
    }

    /**
     * Gets the value of the websiteList property.
     * 
     * @return
     *     possible object is
     *     {@link WebsiteListType }
     *     
     */
    public WebsiteListType getWebsiteList() {
        return websiteList;
    }

    /**
     * Sets the value of the websiteList property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebsiteListType }
     *     
     */
    public void setWebsiteList(WebsiteListType value) {
        this.websiteList = value;
    }

    /**
     * Gets the value of the instantMessagingList property.
     * 
     * @return
     *     possible object is
     *     {@link InstantMessagingListType }
     *     
     */
    public InstantMessagingListType getInstantMessagingList() {
        return instantMessagingList;
    }

    /**
     * Sets the value of the instantMessagingList property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstantMessagingListType }
     *     
     */
    public void setInstantMessagingList(InstantMessagingListType value) {
        this.instantMessagingList = value;
    }

    /**
     * Gets the value of the contactMethodList property.
     * 
     * @return
     *     possible object is
     *     {@link ContactMethodListType }
     *     
     */
    public ContactMethodListType getContactMethodList() {
        return contactMethodList;
    }

    /**
     * Sets the value of the contactMethodList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactMethodListType }
     *     
     */
    public void setContactMethodList(ContactMethodListType value) {
        this.contactMethodList = value;
    }

}
