//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package model.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CoverLetterFieldNames.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CoverLetterFieldNames">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CoverLetter"/>
 *     &lt;enumeration value="CoverLetter.Addressee"/>
 *     &lt;enumeration value="CoverLetter.Addressee.PersonName"/>
 *     &lt;enumeration value="CoverLetter.Letter.Localisation"/>
 *     &lt;enumeration value="CoverLetter.Letter.Localisation.Date"/>
 *     &lt;enumeration value="CoverLetter.Letter.ClosingSalutation"/>
 *     &lt;enumeration value="CoverLetter.Justification"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CoverLetterFieldNames")
@XmlEnum
public enum CoverLetterFieldNames {

    @XmlEnumValue("CoverLetter")
    COVER_LETTER("CoverLetter"),
    @XmlEnumValue("CoverLetter.Addressee")
    COVER_LETTER_ADDRESSEE("CoverLetter.Addressee"),
    @XmlEnumValue("CoverLetter.Addressee.PersonName")
    COVER_LETTER_ADDRESSEE_PERSON_NAME("CoverLetter.Addressee.PersonName"),
    @XmlEnumValue("CoverLetter.Letter.Localisation")
    COVER_LETTER_LETTER_LOCALISATION("CoverLetter.Letter.Localisation"),
    @XmlEnumValue("CoverLetter.Letter.Localisation.Date")
    COVER_LETTER_LETTER_LOCALISATION_DATE("CoverLetter.Letter.Localisation.Date"),
    @XmlEnumValue("CoverLetter.Letter.ClosingSalutation")
    COVER_LETTER_LETTER_CLOSING_SALUTATION("CoverLetter.Letter.ClosingSalutation"),
    @XmlEnumValue("CoverLetter.Justification")
    COVER_LETTER_JUSTIFICATION("CoverLetter.Justification");
    private final String value;

    CoverLetterFieldNames(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CoverLetterFieldNames fromValue(String v) {
        for (CoverLetterFieldNames c: CoverLetterFieldNames.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
