//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Contains a list of references to material attached to this XML instance or outside the scope of it, and which enrich or support the learner�s information.
 * 			
 * 
 * <p>Java class for GenericDocumentationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenericDocumentationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Heading" type="{http://europass.cedefop.europa.eu/Europass}DocumentationHeadingLabelType" minOccurs="0"/>
 *         &lt;element name="InterDocument" type="{http://europass.cedefop.europa.eu/Europass}InterDocumentDocumentationType" minOccurs="0"/>
 *         &lt;element name="IntraDocument" type="{http://europass.cedefop.europa.eu/Europass}IntraDocumentDocumentationType" minOccurs="0"/>
 *         &lt;element name="ExtraDocument" type="{http://europass.cedefop.europa.eu/Europass}ExtraDocumentDocumentationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericDocumentationType", propOrder = {
    "heading",
    "interDocument",
    "intraDocument",
    "extraDocument"
})
public class GenericDocumentationType {

    @XmlElement(name = "Heading")
    protected DocumentationHeadingLabelType heading;
    @XmlElement(name = "InterDocument")
    protected InterDocumentDocumentationType interDocument;
    @XmlElement(name = "IntraDocument")
    protected IntraDocumentDocumentationType intraDocument;
    @XmlElement(name = "ExtraDocument")
    protected ExtraDocumentDocumentationType extraDocument;

    /**
     * Gets the value of the heading property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentationHeadingLabelType }
     *     
     */
    public DocumentationHeadingLabelType getHeading() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentationHeadingLabelType }
     *     
     */
    public void setHeading(DocumentationHeadingLabelType value) {
        this.heading = value;
    }

    /**
     * Gets the value of the interDocument property.
     * 
     * @return
     *     possible object is
     *     {@link InterDocumentDocumentationType }
     *     
     */
    public InterDocumentDocumentationType getInterDocument() {
        return interDocument;
    }

    /**
     * Sets the value of the interDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterDocumentDocumentationType }
     *     
     */
    public void setInterDocument(InterDocumentDocumentationType value) {
        this.interDocument = value;
    }

    /**
     * Gets the value of the intraDocument property.
     * 
     * @return
     *     possible object is
     *     {@link IntraDocumentDocumentationType }
     *     
     */
    public IntraDocumentDocumentationType getIntraDocument() {
        return intraDocument;
    }

    /**
     * Sets the value of the intraDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntraDocumentDocumentationType }
     *     
     */
    public void setIntraDocument(IntraDocumentDocumentationType value) {
        this.intraDocument = value;
    }

    /**
     * Gets the value of the extraDocument property.
     * 
     * @return
     *     possible object is
     *     {@link ExtraDocumentDocumentationType }
     *     
     */
    public ExtraDocumentDocumentationType getExtraDocument() {
        return extraDocument;
    }

    /**
     * Sets the value of the extraDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtraDocumentDocumentationType }
     *     
     */
    public void setExtraDocument(ExtraDocumentDocumentationType value) {
        this.extraDocument = value;
    }

}
