//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package model.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HeadlineTypesEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HeadlineTypesEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="preferred_job"/>
 *     &lt;enumeration value="job_applied_for"/>
 *     &lt;enumeration value="studies_applied_for"/>
 *     &lt;enumeration value="position"/>
 *     &lt;enumeration value="personal_statement"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HeadlineTypesEnumeration")
@XmlEnum
public enum HeadlineTypesEnumeration {

    @XmlEnumValue("preferred_job")
    PREFERRED_JOB("preferred_job"),
    @XmlEnumValue("job_applied_for")
    JOB_APPLIED_FOR("job_applied_for"),
    @XmlEnumValue("studies_applied_for")
    STUDIES_APPLIED_FOR("studies_applied_for"),
    @XmlEnumValue("position")
    POSITION("position"),
    @XmlEnumValue("personal_statement")
    PERSONAL_STATEMENT("personal_statement");
    private final String value;

    HeadlineTypesEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HeadlineTypesEnumeration fromValue(String v) {
        for (HeadlineTypesEnumeration c: HeadlineTypesEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
