//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package model.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InstantMessagingUsesEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InstantMessagingUsesEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="gtalk"/>
 *     &lt;enumeration value="skype"/>
 *     &lt;enumeration value="icq"/>
 *     &lt;enumeration value="aim"/>
 *     &lt;enumeration value="msn"/>
 *     &lt;enumeration value="yahoo"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InstantMessagingUsesEnumeration")
@XmlEnum
public enum InstantMessagingUsesEnumeration {

    @XmlEnumValue("gtalk")
    GTALK("gtalk"),
    @XmlEnumValue("skype")
    SKYPE("skype"),
    @XmlEnumValue("icq")
    ICQ("icq"),
    @XmlEnumValue("aim")
    AIM("aim"),
    @XmlEnumValue("msn")
    MSN("msn"),
    @XmlEnumValue("yahoo")
    YAHOO("yahoo");
    private final String value;

    InstantMessagingUsesEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InstantMessagingUsesEnumeration fromValue(String v) {
        for (InstantMessagingUsesEnumeration c: InstantMessagingUsesEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
