//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Defines a sequence of elements that fully describe a Europass XML document.
 * 			
 * 
 * <p>Java class for LearnerInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LearnerInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identification" type="{http://europass.cedefop.europa.eu/Europass}IdentificationType" minOccurs="0"/>
 *         &lt;element name="Headline" type="{http://europass.cedefop.europa.eu/Europass}HeadlineType" minOccurs="0"/>
 *         &lt;element name="WorkExperienceList" type="{http://europass.cedefop.europa.eu/Europass}WorkExperienceListType" minOccurs="0"/>
 *         &lt;element name="EducationList" type="{http://europass.cedefop.europa.eu/Europass}EducationalExperienceListType" minOccurs="0"/>
 *         &lt;element name="Skills" type="{http://europass.cedefop.europa.eu/Europass}SkillSetType" minOccurs="0"/>
 *         &lt;element name="AchievementList" type="{http://europass.cedefop.europa.eu/Europass}AchievementListType" minOccurs="0"/>
 *         &lt;element name="Documentation" type="{http://europass.cedefop.europa.eu/Europass}IntraDocumentDocumentationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LearnerInfoType", propOrder = {
    "identification",
    "headline",
    "workExperienceList",
    "educationList",
    "skills",
    "achievementList",
    "documentation"
})
public class LearnerInfoType {

    @XmlElement(name = "Identification")
    protected IdentificationType identification;
    @XmlElement(name = "Headline")
    protected HeadlineType headline;
    @XmlElement(name = "WorkExperienceList")
    protected WorkExperienceListType workExperienceList;
    @XmlElement(name = "EducationList")
    protected EducationalExperienceListType educationList;
    @XmlElement(name = "Skills")
    protected SkillSetType skills;
    @XmlElement(name = "AchievementList")
    protected AchievementListType achievementList;
    @XmlElement(name = "Documentation")
    protected IntraDocumentDocumentationType documentation;

    /**
     * Gets the value of the identification property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationType }
     *     
     */
    public IdentificationType getIdentification() {
        return identification;
    }

    /**
     * Sets the value of the identification property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationType }
     *     
     */
    public void setIdentification(IdentificationType value) {
        this.identification = value;
    }

    /**
     * Gets the value of the headline property.
     * 
     * @return
     *     possible object is
     *     {@link HeadlineType }
     *     
     */
    public HeadlineType getHeadline() {
        return headline;
    }

    /**
     * Sets the value of the headline property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadlineType }
     *     
     */
    public void setHeadline(HeadlineType value) {
        this.headline = value;
    }

    /**
     * Gets the value of the workExperienceList property.
     * 
     * @return
     *     possible object is
     *     {@link WorkExperienceListType }
     *     
     */
    public WorkExperienceListType getWorkExperienceList() {
        return workExperienceList;
    }

    /**
     * Sets the value of the workExperienceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkExperienceListType }
     *     
     */
    public void setWorkExperienceList(WorkExperienceListType value) {
        this.workExperienceList = value;
    }

    /**
     * Gets the value of the educationList property.
     * 
     * @return
     *     possible object is
     *     {@link EducationalExperienceListType }
     *     
     */
    public EducationalExperienceListType getEducationList() {
        return educationList;
    }

    /**
     * Sets the value of the educationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationalExperienceListType }
     *     
     */
    public void setEducationList(EducationalExperienceListType value) {
        this.educationList = value;
    }

    /**
     * Gets the value of the skills property.
     * 
     * @return
     *     possible object is
     *     {@link SkillSetType }
     *     
     */
    public SkillSetType getSkills() {
        return skills;
    }

    /**
     * Sets the value of the skills property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkillSetType }
     *     
     */
    public void setSkills(SkillSetType value) {
        this.skills = value;
    }

    /**
     * Gets the value of the achievementList property.
     * 
     * @return
     *     possible object is
     *     {@link AchievementListType }
     *     
     */
    public AchievementListType getAchievementList() {
        return achievementList;
    }

    /**
     * Sets the value of the achievementList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AchievementListType }
     *     
     */
    public void setAchievementList(AchievementListType value) {
        this.achievementList = value;
    }

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link IntraDocumentDocumentationType }
     *     
     */
    public IntraDocumentDocumentationType getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntraDocumentDocumentationType }
     *     
     */
    public void setDocumentation(IntraDocumentDocumentationType value) {
        this.documentation = value;
    }

}
