//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package model.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LinguisticExperienceAreasEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LinguisticExperienceAreasEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="studying_training_language"/>
 *     &lt;enumeration value="work_language"/>
 *     &lt;enumeration value="living_traveling_language"/>
 *     &lt;enumeration value="mediating_groups_language"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LinguisticExperienceAreasEnumeration")
@XmlEnum
public enum LinguisticExperienceAreasEnumeration {

    @XmlEnumValue("studying_training_language")
    STUDYING_TRAINING_LANGUAGE("studying_training_language"),
    @XmlEnumValue("work_language")
    WORK_LANGUAGE("work_language"),
    @XmlEnumValue("living_traveling_language")
    LIVING_TRAVELING_LANGUAGE("living_traveling_language"),
    @XmlEnumValue("mediating_groups_language")
    MEDIATING_GROUPS_LANGUAGE("mediating_groups_language");
    private final String value;

    LinguisticExperienceAreasEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LinguisticExperienceAreasEnumeration fromValue(String v) {
        for (LinguisticExperienceAreasEnumeration c: LinguisticExperienceAreasEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
