//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package model.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PositionNames.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PositionNames">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="left-align"/>
 *     &lt;enumeration value="right-align"/>
 *     &lt;enumeration value="middle-align"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PositionNames")
@XmlEnum
public enum PositionNames {

    @XmlEnumValue("left-align")
    LEFT_ALIGN("left-align"),
    @XmlEnumValue("right-align")
    RIGHT_ALIGN("right-align"),
    @XmlEnumValue("middle-align")
    MIDDLE_ALIGN("middle-align");
    private final String value;

    PositionNames(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PositionNames fromValue(String v) {
        for (PositionNames c: PositionNames.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
