//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package model.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sector-level1.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="sector-level1">
 *   &lt;restriction base="{http://europass.cedefop.europa.eu/NACE}sector">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="D"/>
 *     &lt;enumeration value="E"/>
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="H"/>
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="J"/>
 *     &lt;enumeration value="K"/>
 *     &lt;enumeration value="L"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="O"/>
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="Q"/>
 *     &lt;enumeration value="R"/>
 *     &lt;enumeration value="S"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="U"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "sector-level1", namespace = "http://europass.cedefop.europa.eu/NACE")
@XmlEnum
public enum SectorLevel1 {


    /**
     * Tar\u0131m, ormanc\u0131l\u0131k ve bal\u0131k\u00e7\u0131l\u0131k
     * 
     */
    A,

    /**
     * Madencilik ve ta\u015f oca\u011f\u0131 
     * 
     */
    B,

    /**
     * Imalat
     * 
     */
    C,

    /**
     * Elektirik, gaz, buhar ve klima tedariki
     * 
     */
    D,

    /**
     * Su tedariki, \u00e7\u00f6pl\u00fck, at\u0131m y\u00f6netimi ve su kalitesinin iyile\u015ftirilmesi
     * 
     */
    E,

    /**
     * In\u015faat
     * 
     */
    F,

    /**
     * Toptan Ve Perakende Sat\u0131\u015f, Motorlu Ara\u00e7lar\u0131n Tamiri
     * 
     */
    G,

    /**
     * Ta\u015f\u0131mac\u0131l\u0131k Ve Depolama
     * 
     */
    H,

    /**
     * Bar\u0131nma Ve G\u0131da Hizmeti
     * 
     */
    I,

    /**
     * Bilgi Ve Ileti\u015fim
     * 
     */
    J,

    /**
     * Finans Ve Sigorta Faaliyetleri
     * 
     */
    K,

    /**
     * Gayrimenkul Sekt\u00f6r\u00fc Faaliyetleri
     * 
     */
    L,

    /**
     * Mesleki, Bilimsel Ve Teknik Faaliyetler
     * 
     */
    M,

    /**
     * Idari Ve Destek Hizmetleri Faaliyetleri
     * 
     */
    N,

    /**
     * Kamu Y\u00f6netimi Ve Savunma; Zorunlu Sosyal G\u00fcvenlik
     * 
     */
    O,

    /**
     * E\u011fitim
     * 
     */
    P,

    /**
     * Insan Sa\u011fl\u0131\u011f\u0131 Ve Sosyal \u00c7al\u0131\u015fma Faaliyetleri
     * 
     */
    Q,

    /**
     * Sanat Ve E\u011flence
     * 
     */
    R,

    /**
     * Di\u011fer Hizmet Faaliyetleri
     * 
     */
    S,

    /**
     * Hane Halk\u0131n\u0131 I\u015f G\u00fcc\u00fc Olarak Kullanan Faaliyetler; Pazarlananan Mallar - Ve Hizmetler- \u015eahsi Kullan\u0131m I\u00e7in \u00dcretim Faaliyetleri
     * 
     */
    T,

    /**
     * \u00dclke Yasalar\u0131na Dahil Olmayan \u00d6rg\u00fct Ve Te\u015fkilatlar\u0131n Faaliyetleri
     * 
     */
    U;

    public String value() {
        return name();
    }

    public static SectorLevel1 fromValue(String v) {
        return valueOf(v);
    }

}
