//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 04:21:20 PM EEST 
//


package model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Contains a sequence of skills and competences that the learner has acquired during any formal or informal experience.
 * 			
 * 
 * <p>Java class for SkillSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SkillSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Linguistic" type="{http://europass.cedefop.europa.eu/Europass}LinguisticSkillType" minOccurs="0"/>
 *         &lt;element name="Communication" type="{http://europass.cedefop.europa.eu/Europass}GenericSkillType" minOccurs="0"/>
 *         &lt;element name="Organisational" type="{http://europass.cedefop.europa.eu/Europass}GenericSkillType" minOccurs="0"/>
 *         &lt;element name="JobRelated" type="{http://europass.cedefop.europa.eu/Europass}GenericSkillType" minOccurs="0"/>
 *         &lt;element name="Computer" type="{http://europass.cedefop.europa.eu/Europass}ComputerSkillType" minOccurs="0"/>
 *         &lt;element name="Driving" type="{http://europass.cedefop.europa.eu/Europass}DrivingSkillType" minOccurs="0"/>
 *         &lt;element name="Other" type="{http://europass.cedefop.europa.eu/Europass}GenericSkillType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SkillSetType", propOrder = {
    "linguistic",
    "communication",
    "organisational",
    "jobRelated",
    "computer",
    "driving",
    "other"
})
public class SkillSetType {

    @XmlElement(name = "Linguistic")
    protected LinguisticSkillType linguistic;
    @XmlElement(name = "Communication")
    protected GenericSkillType communication;
    @XmlElement(name = "Organisational")
    protected GenericSkillType organisational;
    @XmlElement(name = "JobRelated")
    protected GenericSkillType jobRelated;
    @XmlElement(name = "Computer")
    protected ComputerSkillType computer;
    @XmlElement(name = "Driving")
    protected DrivingSkillType driving;
    @XmlElement(name = "Other")
    protected GenericSkillType other;

    /**
     * Gets the value of the linguistic property.
     * 
     * @return
     *     possible object is
     *     {@link LinguisticSkillType }
     *     
     */
    public LinguisticSkillType getLinguistic() {
        return linguistic;
    }

    /**
     * Sets the value of the linguistic property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinguisticSkillType }
     *     
     */
    public void setLinguistic(LinguisticSkillType value) {
        this.linguistic = value;
    }

    /**
     * Gets the value of the communication property.
     * 
     * @return
     *     possible object is
     *     {@link GenericSkillType }
     *     
     */
    public GenericSkillType getCommunication() {
        return communication;
    }

    /**
     * Sets the value of the communication property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericSkillType }
     *     
     */
    public void setCommunication(GenericSkillType value) {
        this.communication = value;
    }

    /**
     * Gets the value of the organisational property.
     * 
     * @return
     *     possible object is
     *     {@link GenericSkillType }
     *     
     */
    public GenericSkillType getOrganisational() {
        return organisational;
    }

    /**
     * Sets the value of the organisational property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericSkillType }
     *     
     */
    public void setOrganisational(GenericSkillType value) {
        this.organisational = value;
    }

    /**
     * Gets the value of the jobRelated property.
     * 
     * @return
     *     possible object is
     *     {@link GenericSkillType }
     *     
     */
    public GenericSkillType getJobRelated() {
        return jobRelated;
    }

    /**
     * Sets the value of the jobRelated property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericSkillType }
     *     
     */
    public void setJobRelated(GenericSkillType value) {
        this.jobRelated = value;
    }

    /**
     * Gets the value of the computer property.
     * 
     * @return
     *     possible object is
     *     {@link ComputerSkillType }
     *     
     */
    public ComputerSkillType getComputer() {
        return computer;
    }

    /**
     * Sets the value of the computer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComputerSkillType }
     *     
     */
    public void setComputer(ComputerSkillType value) {
        this.computer = value;
    }

    /**
     * Gets the value of the driving property.
     * 
     * @return
     *     possible object is
     *     {@link DrivingSkillType }
     *     
     */
    public DrivingSkillType getDriving() {
        return driving;
    }

    /**
     * Sets the value of the driving property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrivingSkillType }
     *     
     */
    public void setDriving(DrivingSkillType value) {
        this.driving = value;
    }

    /**
     * Gets the value of the other property.
     * 
     * @return
     *     possible object is
     *     {@link GenericSkillType }
     *     
     */
    public GenericSkillType getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericSkillType }
     *     
     */
    public void setOther(GenericSkillType value) {
        this.other = value;
    }

}
